Allow change of owner in resign
ssvlabs/dkg-spec pull request #16
Opened 2024-10-28 14:50 UTC by alan-ssvlabs

remove address check in proof validation and add address check in reshare only, to allow resign to change owner.

2024-10-29 10:29 UTC, GalRogozinski requested changes

2024-10-29 10:29 UTC, GalRogozinski commented on testing/result_test.go
> -	t.Run("invalid proof owner address", func(t *testing.T) {
If this was deleted, shouldn't a new test be added to compensate?

2024-10-29 15:41 UTC, alan-ssvlabs commented on reshare.go
> +	}
agree, updated.

2024-10-29 15:43 UTC, alan-ssvlabs commented
Tests for owner address are added. 

BTW build failed for some reason that I don't understand and it also failed currently in the master branch, is it due to some previous commits?

2024-11-07 13:31 UTC, GalRogozinski approved these changes

2024-11-07 13:31 UTC, merged